drivers: devfreq: remove unused variable
../drivers/devfreq/helio-dvfsrc-v3/helio-dvfsrc-sysfs.c:254:23: error: variable 'dvfsrc' set but not used [-Werror,-Wunused-but-set-variable]
        struct helio_dvfsrc *dvfsrc;
                             ^
1 error generated.

Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>